music_app/website/auth.py
from flask import Blueprint, url_for, redirect, render_template, request, flash, session
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db



auth = Blueprint('auth', __name__)


@auth.route('/', methods = ['GET', 'POST'])
def login():

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email = email).first()
        if user:
            if check_password_hash(user.password, password):

                session['user_name'] = user.first_name
                session['user'] = user.id
                return redirect(url_for('views.home'))
            
            else:
                flash('Incorrect Password, Try again', category='error')
        else:
            flash("You dont have an account with this email id. Please create one.", category='error')


    return render_template("login.html")


@auth.route('/sign_up', methods = ['GET', 'POST'])





def  sign_up():
    if request.method == 'POST':
        email = request.form['email']
        fname = request.form['firstname']
        lname = request.form['lastname']
        password1 = request.form['password1']
        password2 = request.form['password2']
        
        session['user_name'] = fname
        
        # Check if the email already exists in the database
        existing_user = User.query.filter_by(email=email).first()

        if existing_user:
            flash('You already creat an account. You should login with this email id or use a different email id.', category='error')
        elif len(email) < 5:
            flash('email must be greater than 4 charachter', category='error')
        elif len(fname) < 3:
            flash('First name must be greater than 2 charachter', category='error')
        elif password1 != password2:
            flash('Your passwords should be match', category='error')
        elif len(password1) < 4:
            flash('minimum length of password should be 4', category='error')
        else:

            new_user = User(email= email, first_name = fname, password = generate_password_hash(password1, method= 'sha256') , last_name = lname )
            db.session.add(new_user)
            db.session.commit()
            session['user'] = new_user.id
            return redirect(url_for("views.home"))
            

    

    return render_template("signup.html")

@auth.route('/logout')

def logout():
    user_name = session.get('user_name')
    user = session.get('user')
    if user_name:
        session.pop('user_name', None)
        session.pop('user', None)
    return redirect(url_for('auth.login'))

music_app/website/views.py
from flask import Blueprint, render_template, url_for, session, redirect, render_template, flash, request
from . import db
from .models import Song, Rating, Playlist, Album, User
from os.path import join, dirname
from os import makedirs
from .api import SongResource





views = Blueprint('views', __name__)





@views.route('/home')
def home():
    user_name = session.get('user_name')
    if user_name:
        songs = Song.query.all()
        return render_template("home.html", user_name=user_name, songs=songs)
    else:
        flash('Please Login First')
    return redirect(url_for('auth.login'))



@views.route('/filter_songs', methods=['POST'])
def filter_songs():
    user_name = session.get('user_name')
    selected_genre = request.form.get('genre')

    if selected_genre == 'All':
        songs = Song.query.all()
    else:
        songs = Song.query.filter_by(genre=selected_genre).all()

    return render_template("home.html", user_name=user_name, songs=songs, selected_songs= selected_genre)





@views.route('/upload_song', methods=['GET', 'POST'])
def upload_song():
    user_name = session.get('user_name')
    
    if not user_name:
        flash('Please Login First')
        return redirect(url_for('auth.login'))
    
    songs = Song.query.filter_by(user_id = session.get('user'))
    if request.method == 'POST':
            user_id = session.get('user')
            user= User.query.get(user_id)
            if user.white_list:
                song_name = request.form['songName']
                singer_name = request.form['singer_name']
                lyrics = request.form['lyrics']
                duration = request.form['duration']
                genre = request.form['genre']
                song_file = request.files['song']
                user_id = session['user']



                print(song_file.filename)
                if song_file:
                # Create a new song instance and populate its attributes
                    new_song = Song(
                        name=song_name,
                        singer=singer_name,
                        lyrics=lyrics,
                        genre = genre,
                        duration=duration,
                        user_id= user_id, 


                    )

                    # Add the song to the database
                    db.session.add(new_song)
                    db.session.commit()

                # Save the song file to a storage location
                    #song_file.save('website/static' + song_file.filename)
                    #song_file.save(join('website', 'static', 'songs', song_file.filename))
                    save_path = join('website', 'static', 'songs', song_file.filename)
                    # Ensure the directory exists, create it if not
                    makedirs(dirname(save_path), exist_ok=True)
                    song_file.save(save_path)


                    flash('Song uploaded successfully', 'success')
                    return redirect(url_for('views.upload_song'))
                

            
                else:
                    flash('No file was uploaded', 'error')
            
            else:
                flash("You are in a Black List, You can't upload a Song", 'error')



    return render_template("upload_song.html", user_name=user_name, songs = songs)









@views.route('/rate_song/<int:song_id>', methods=['POST'])
def rate_song(song_id):
    user_id = session.get('user')

    # Check if the user has already rated this song
    existing_rating = Rating.query.filter_by(user_id=user_id, song_id=song_id).first()

    if existing_rating:
        flash('You have already rated this song.', 'error')
    else:
        # Get the rating from the form
        rating = int(request.form.get('rating'))

        if 1 <= rating <= 5:
            # Create a new rating record
            new_rating = Rating(user_id=user_id, song_id=song_id, rating=rating)

            # Update the song's total ratings and the number of ratings
            song = Song.query.get(song_id)
            song.ratings = (song.ratings * song.num_ratings + rating) / (song.num_ratings + 1)
            song.num_ratings += 1

            # Commit the changes to the database
            db.session.add(new_rating)
            db.session.commit()

            flash(f'You rated the song with {rating} stars.', 'success')
        else:
            flash('Invalid rating value. Please rate the song from 1 to 5 stars.', 'error')

    return redirect(url_for('views.home'))



@views.route('/lyrics/<int:song_id>')
def lyrics(song_id):
    song = Song.query.get(song_id)
    return render_template('lyrics.html', song=song)




@views.route('/edit_song/<int:song_id>', methods = ['POST','GET'])
def edit_song(song_id):
    song = Song.query.get(song_id)
    if request.method == 'GET':
        return render_template('edit_song.html', song=song)
    else:
        name = request.form.get('name')
        lyrics = request.form.get('lyrics')
        singer = request.form.get('singer')

        # Update the song details
        song.name = name
        song.lyrics = lyrics
        song.singer = singer

        # Commit changes to the database
        db.session.commit()

        flash('Song updated successfully', 'success')
        return redirect(url_for('views.upload_song'))








@views.route('/delete_song/<int:song_id>', methods=['POST'])
def delete_song(song_id):
    # Get the current user's ID or any other way to identify the user
    user_id = session.get('user')

    if user_id:
        if request.method == 'POST':
            try:
            # Retrieve the song from the database based on song_id and user_id
                song_to_delete = Song.query.filter_by(id=song_id, user_id=user_id).first()

                if song_to_delete:
                    # Mark the song for deletion
                    print(f"Deleting song: {song_to_delete.name}")
                    db.session.delete(song_to_delete)
                    db.session.commit()
                    flash('Song deleted successfully', 'success')
                else:
                    flash('Song not found or you do not have permission to delete it', 'error')
            except Exception as e:
                flash(f'Error deleting song: {str(e)}', 'error')

    else:
        flash('Please log in to delete a song', 'error')

    return redirect(url_for('views.upload_song'))






@views.route('/user_summary')
def user_summary():

    user_id = session.get('user')
    user_name = session.get('user_name')
    user = User.query.get(user_id)

    # Number of songs uploaded by the user
    num_songs = len(user.songs)

    # Number of playlists created by the user 
    num_playlists = len(user.playlists)

    # Number of albums created by the user
    num_albums = len(user.albums)

    # Average rating of all songs uploaded by the user
    total_rating = 0
    for song in user.songs:
        total_rating += song.ratings
    average_rating = total_rating / num_songs if num_songs > 0 else 0

    # The song(s) with the highest rating uploaded by the user
    highest_rated_songs = (
        Song.query.filter_by(user_id=user_id)
        .order_by(Song.ratings.desc())
        .limit(5)  # You can limit to a specific number of top-rated songs
        .all()
    )

    return render_template(
        'user_summary.html',
        user=user,
        user_name = user_name,
        num_songs=num_songs,
        num_playlists=num_playlists,
        num_albums=num_albums,
        average_rating=average_rating,
        highest_rated_songs=highest_rated_songs,
    )



@views.route('/privacy_policy')
def privacy_policy():
    user_name = session.get('user_name')

    return render_template('privacy_policy.html', user_name = user_name)





@views.route('/search_music', methods=['GET'])
def search_music():
    query = request.args.get('query', '')

    if query:
        user_name = session.get('user_name')
        search_results = db.session.query(Song).filter(Song.name.ilike(f'%{query}%')).all()
    else:

        search_results = []

    return render_template('search_music.html', query=query, results=search_results, user_name=user_name)

music_app/website/templates/add_songs_to_album.html
{% extends 'base.html' %}

{% block title %} Add Songs to Album  {% endblock %}

{% block search %} {% endblock %}

{% block content %}
<div class="container">
    <center><h1 style="font-family: cursive;"> Add Songs to {{ album.name }} </h1></center>
    <div class="row">
        <form method="post" action="{{ url_for('album.add_songs_to_album', album_id=album.id) }}">
            <label>Select Songs to Add:</label>
            {% for song in remaining_songs %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="selected_songs" value="{{ song.id }}">
                    <label class="form-check-label" for="selected_songs_{{ song.id }}">
                        {{ song.name }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Add Selected Songs</button>
        </form>
    </div>
</div>
{% endblock %}

music_app/website/templates/add_to_playlist.html
{% extends "base.html" %}

{% block title %} Add To Playlist Page {% endblock %}

{% block search %} 

{% endblock %}


{% block content %}


 <div style="margin-top: 100px; padding: 20px;">
<form method="POST" action="{{ url_for('playlist.add_to_playlist', song_id=song_id) }}">
   
   <div style="border: 2px solid black; padding: 20px;">
    <h3>Select Playlist</h3>
    <label for="playlist">Select an existing playlist:</label>
    <select name="playlist" id="playlist" style="width: 150px;">
        <option value="" disabled selected>Select a playlist</option>
        {% for playlist in playlists %}
            <option value="{{ playlist.id }}">{{ playlist.name }}</option>
        {% endfor %}
    </select>
    </div>


    <div style="border: 2px solid black; margin-top: 30px; padding: 20px;">
    <h3>Create a Playlist</h3>

    <label for="new_playlist">Create a new playlist:</label>
    <input type="text" name="new_playlist" id="new_playlist" placeholder="Enter a new playlist name">
</div>


    <div style="margin-top: 20px;">
    <button type="submit" class="btn btn-dark" > Add Song </button>
    </div>


</form>
</div>

{% endblock %}

music_app/website/templates/admin_album_songs.html
{% extends 'admin_base.html' %}

{% block search %} 

<form class="d-flex" method="GET" action="{{ url_for('views.search_music') }}" >
    <input class="form-control me-2"  name="query" type="text" placeholder="Search">
    <button class="btn btn-primary" type="submit">Search</button>
</form>

{% endblock %}

{% block content%}
<div class="container">
    <center><h1 style="font-family: cursive;"> {{album.name}} </h1></center>
    <div class="row">
        {% for song in songs %}
        <div class="card mt-3 mb-3" style="border: 2px solid black;">
            <div class="card-header">
                {{ song.name }}
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <audio controls style="width: 100%;">
                        <source src="{{ url_for('static', filename='songs/' + song.name) }}" type="audio/mpeg">
                        Your browser does not support the audio element.
                    </audio>
                </h5>
                <p class="card-text">{{ song.singer }}</p>


                <form action="{{ url_for('admin.remove_from_album', song_id=song.id, album_id=album.id) }}" method="post">
                    
                    <button type="submit" class="btn btn-danger ">Remove From Album</button>
                </form>


            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

music_app/website/templates/admin_base.html
<!DOCTYPE html >
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


        
        <title>{% block title %}Base Template {% endblock %} </title>
</head>

<body style="background-color: gainsboro;" >
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top mb-4">


        <div class="container-fluid mb-4">
            <a class="navbar-brand" href="javascript:void(0)"><svg xmlns="http://www.w3.org/2000/svg" width="30"
                    height="30" fill="currentColor" class="bi bi-music-note-beamed" viewBox="0 0 16 16">
                    <path
                        d="M6 13c0 1.105-1.12 2-2.5 2S1 14.105 1 13c0-1.104 1.12-2 2.5-2s2.5.896 2.5 2zm9-2c0 1.105-1.12 2-2.5 2s-2.5-.895-2.5-2 1.12-2 2.5-2 2.5.895 2.5 2z" />
                    <path fill-rule="evenodd" d="M14 11V2h1v9h-1zM6 3v10H5V3h1z" />
                    <path d="M5 2.905a1 1 0 0 1 .9-.995l8-.8a1 1 0 0 1 1.1.995V3L5 4V2.905z" />
                </svg> </i></a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav me-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('admin.admin_dashboard')}}"> Dashboard </a>
                    </li>




                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('admin.songs')}}">Songs </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('admin.admin_albums')}}">
                            <p>Albums </p>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('admin.user_list')}}">Users</a>
                    </li>                    

                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('admin.logout')}}">Logout</a>
                    </li>



                </ul>


                {% block search %} 

                <form class="d-flex" method="GET" action="{{ url_for('admin.search_music') }}" >
                    <input class="form-control me-2"  name="query" type="text" placeholder="Search">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                
                {% endblock %}
            </div>
        </div>
    </nav>








    <div style="margin-top: 50px; padding: 20px; margin-bottom: 50px;">
        <div class="container-fluid mt-5 ">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-bs-dismiss="alert" style="float: right;">
                    <span area-hidden="true">&times;</span>
                </button>
            </div>

            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

        {% block content %} {%  endblock %}

    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

music_app/website/templates/admin_dashboard.html
{% extends 'admin_base.html' %}


{% block title %}Admin Dashboard {% endblock %}

{% block search %} {% endblock %}


{% block content %}

<div class="row">
    <div class="col-md-4">
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">Total Users</h2>
                <p class="card-text lead">{{ num_users }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">Total Albums</h2>
                <p class="card-text lead">{{ num_albums }}</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">Number Of Creators</h2>
                <p class="card-text lead">{{ num_users_uploaded_songs }}</p>
            </div>
        </div>
    </div>

</div>



<div class="row">
    <div class="col-md-8">
      <div class="card mb-8">
            <div class="card-body">
                <h2 class="card-title">Top-Rated Songs</h2>
                <ul class="list-group">
                    {% for song in top_rated_songs %}
                    <li class="list-group-item">{{ song.name }} (Average Rating: {{ song.ratings|round(2) }}) ,      Singer : {{ song.singer }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
       <div class="card mb-4"> 
            <div class="card-body">
                <h2 class="card-title">Top Songs by Playlist Count</h2>
                <img src="data:image/png;base64,{{ img_data }}" alt="Playlist Chart" class="img-fluid">
            </div>
        </div>
    </div>
</div>









{% endblock %}

music_app/website/templates/admin_users.html
{%  extends 'admin_base.html' %}

{% block title %} Users Details {% endblock %}


{% block search %} 

<form class="d-flex" method="GET" action="{{ url_for('admin.search_user') }}" >
    <input class="form-control me-2"  name="query" type="text" placeholder="Search">
    <button class="btn btn-primary" type="submit">Search</button>
</form>

{% endblock %}







{% block content %}



<div class="container">
    <h2>User List</h2>
    <table class="table">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>White List Status</th>
                <th>User Status </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ "Whitelisted" if user.white_list else "Blacklisted" }}</td>
                    <td>{{ "Creator" if is_creator(user) else "Normal" }}</td>
                    <td>
                        <form method="post" action="{{ url_for('admin.toggle_white_list', user_id=user.id) }}">
                            <button type="submit" class="btn btn-primary">
                                {% if user.white_list %}
                                    Add to Blacklist
                                {% else %}
                                    Add to Whitelist
                                {% endif %}
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

music_app/website/templates/base.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>
    {% block title %}Base Template {% endblock %}
  </title>
</head>

<body  style="background-color: blanchedalmond;">

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top mb-4">


    <div class="container-fluid mb-4">
      <a class="navbar-brand" href="javascript:void(0)"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
          fill="currentColor" class="bi bi-music-note-beamed" viewBox="0 0 16 16">
          <path
            d="M6 13c0 1.105-1.12 2-2.5 2S1 14.105 1 13c0-1.104 1.12-2 2.5-2s2.5.896 2.5 2zm9-2c0 1.105-1.12 2-2.5 2s-2.5-.895-2.5-2 1.12-2 2.5-2 2.5.895 2.5 2z" />
          <path fill-rule="evenodd" d="M14 11V2h1v9h-1zM6 3v10H5V3h1z" />
          <path d="M5 2.905a1 1 0 0 1 .9-.995l8-.8a1 1 0 0 1 1.1.995V3L5 4V2.905z" />
        </svg> </i></a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('views.home')}}">{{ user_name}} </a>
          </li>



          
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('views.user_summary')}}">Profile Summary </a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{{url_for('album.view_albums')}}">
              <p>Albums </p>
            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{{url_for('views.upload_song')}}">
              <p>Upload Song </p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('playlist.select_playlist')}}">
              <p>Playlist </p>
            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
          </li>


        </ul>

        {% block search %}
        
        <form class="d-flex" method="GET" action="{{ url_for('views.search_music') }}" >
          <input class="form-control me-2"  name="query" type="text" placeholder="Search">
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
        {% endblock %}


      </div>
    </div>
  </nav>

  <div style="margin-top: 50px; padding: 20px; margin-bottom: 50px;">
    <div class="container-fluid mt-5 ">


      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-bs-dismiss="alert" style="float: right;">
          <span area-hidden="true">&times;</span>
        </button>
      </div>

      {% endfor %}
      {% endif %}
      {% endwith %}

      {% block content %}
      {% endblock %}
    </div>

  </div>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('views.privacy_policy')}}" >Privacy Policy</a>
    </div>
  </nav>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>

</html>

music_app/website/templates/search_album.html
{% extends "base.html" %}

{% block title %} Searched Albums {% endblock %}

{% block search %} {% endblock %}



{% block content %}

<a href="{{ url_for('album.create_album') }}" class="btn btn-primary">Create New Album</a>

<div class="container">
    <center><h1 style="font-family: cursive;"> Albums </h1></center>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for album in results %}
        <div class="col">
            <div class="card" >
                <a href="{{ url_for('album.view_album_songs', album_id=album.id) }}" style="text-decoration: none; color: inherit;">
                    <div class="card-body" >
                        <h5 class="card-title">{{ album.name }}</h5>
                        <p class="card-text">Songs in Album: {{ album.album_songs|length }}</p>
                    </div>
                </a>
                {% if album.user_id == session.get('user') %}
                <form action="{{ url_for('album.delete_album', album_id=album.id) }}" method="post">
                    <button type="submit" class="btn btn-danger" style="margin: 5px;">Delete</button>
                </form>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

music_app/website/templates/search_playlist.html
{% extends "base.html" %}

{% block title %} Playlist Selection Page {% endblock %}

{% block search %} 

{% endblock %}



{% block content %}
<div class="container">
    <center><h1 style="font-family: cursive;"> Your Playlists </h1></center>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for playlist in results %}
        <div class="col">
            <div class="card">
                <a href="{{ url_for('playlist.user_selected_playlist', playlist_name=playlist.name) }}" style="text-decoration: none; color: inherit;">
                <div class="card-body" style="background-color: rgb(255, 220, 226); border: 1px solid;">
                    <h5 class="card-title">{{ playlist.name }}</h5>
                    <p class="card-text">No of Songs: {{ playlist.songs|length }}</p>
                </a>
                    <a href="{{ url_for('playlist.delete_playlist', playlist_name=playlist.name) }}"
                        class="btn btn-danger">Delete Playlist</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

music_app/website/templates/upload_song.html
{% extends "base.html" %}

{% block title %} upload/Delete Page {% endblock %}

{% block search %} {% endblock %}


{% block content %}



<div class="mt-5" style="border: 5px solid black; ">

  <h1 class="mt-3">
    <center>To Upload A Song</center>
  </h1>
  <form method="POST" style="margin: 150px; margin-top: 70px;" action="{{ url_for('views.upload_song') }}"
    enctype="multipart/form-data">
    <div class="mb-3">
      <label for="song_name" class="form-label">Song Name</label>
      <input type="text" class="form-control" id="song_name" name="songName" placeholder="Enter Song Name" required>
    </div>
    <div class="mb-3">
      <label for="singer_name" class="form-label">Singer Name</label>
      <input type="text" class="form-control" id="singer_name" name="singer_name" placeholder=" Enter Singer Name">
    </div>



    <div class="mb-3">
      <label for="genre" class="form-label">Genre</label>
      <select class="form-select" id="genre" name="genre" required>
        <option value="" disabled selected>Select Genre</option>
        <option value="Rock">Rock</option>
        <option value="Pop">Pop</option>
        <option value="Wedding">Wedding</option>
        <option value="Emo">Emo</option>
        <option value="Romentic">Romentic</option>
        <option value="Hip-Hop">Hip-Hop</option>
        <option value="Other">Other</option>

      </select>
    </div>

    <div class="mb-3">
      <textarea id="lyrics" name="lyrics" rows="5" cols="100" placeholder="Write Lyrics Here"></textarea>
    </div>

    <div class="mb-3">
      <label for="duration" class="form-label">Duration</label>
      <input id="duration" name="duration" pattern="[0-9]{1,3}:[0-5][0-9]" placeholder="e.g., 03:30" required>
    </div>

    <div class="mb-3  mt-3 card  bg-light text-dark ">

      <input class="form-control" type="file" name="song" accept="audio/mpeg, audio/ogg, audio/wav" required>
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>

  </form>

</div>










<div class="mt-3 mb-3" style="border: 5px solid black;">
  <h1 class="mt-3 mb-3">
    <center>Uploaded Songs</center>
   </h1>

  <div class="container">
    <div class="row">
      {% for song in songs %}
      <div class="card mt-3 mb-3" style="border: 2px solid black;">
        <div class="card-header">
          {{ song.name }}
        </div>
        <div class="card-body ">
          <h5 class="card-title"><audio controls style="width: 100%;">
              <source src="{{ url_for('static', filename='songs/' + song.name) }}" type="audio/mpeg">
              Your browser does not support the audio element.
            </audio></h5>
          <p class="card-text">{{ song.singer }}
            <form action="{{ url_for('views.edit_song', song_id=song.id) }}" method="get">
              <button type="submit" class="btn btn-primary float-right mb-3">Edit</button>
            </form>
          <form action="{{ url_for('views.delete_song', song_id=song.id) }}" method="post">
            <button type="submit" class="btn btn-danger float-right">Delete</button>
          </form>
          </p>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>

</div>


{% endblock %}